# Generated by Django 3.0.3 on 2020-02-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vsd1C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.CharField(max_length=20)),
                ('name_1c', models.CharField(max_length=124)),
                ('q_pack', models.CharField(max_length=48)),
                ('data_1c', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Отбор с 1С',
                'verbose_name_plural': 'Отбор с 1С',
            },
        ),
        migrations.CreateModel(
            name='VsdMerc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_1c', models.CharField(max_length=128)),
                ('name_merc', models.CharField(max_length=128)),
                ('w_in_pack', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
            options={
                'verbose_name': 'БД Меркурий',
                'verbose_name_plural': 'БД Меркурий',
            },
        ),
    ]
