# Generated by Django 3.0.3 on 2020-02-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mk_rc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vsd1c',
            name='q_pack',
        ),
    ]
