# Generated by Django 3.0.3 on 2020-02-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mk_rc', '0002_remove_vsd1c_q_pack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsd1c',
            name='data_1c',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vsd1c',
            name='name_1c',
            field=models.CharField(blank=True, max_length=124),
        ),
        migrations.AlterField(
            model_name='vsdmerc',
            name='name_1c',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='vsdmerc',
            name='name_merc',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='vsdmerc',
            name='w_in_pack',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=3),
        ),
    ]
