# Generated by Django 3.0.3 on 2020-03-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mk_rc', '0003_auto_20200221_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsdmerc',
            name='w_in_pack',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10),
        ),
    ]
