# Generated by Django 3.0 on 2019-12-09 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Legal_entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=120, verbose_name='Юр.Лицо')),
            ],
            options={
                'verbose_name': 'Юр.Лицо',
                'verbose_name_plural': 'Юр.Лицо',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=120, verbose_name='Супервайзер')),
            ],
            options={
                'verbose_name': 'Супервайзер',
                'verbose_name_plural': 'Супервайзеры',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_id', models.IntegerField(blank=True, verbose_name='№ маг.')),
                ('address', models.CharField(blank=True, max_length=120, verbose_name='Адрес')),
                ('telephone', models.CharField(blank=True, max_length=120, verbose_name='Телефон')),
                ('format', models.IntegerField(blank=True, verbose_name='Формат')),
                ('legal_entity', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='batyr.Legal_entity', verbose_name='Юр.Лицо')),
                ('supervisor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='batyr.Supervisor', verbose_name='Супервайзер')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
    ]
