# Generated by Django 3.0 on 2019-12-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batyr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='telephone',
        ),
    ]
